<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Carbon;

class MenuSeeder extends Seeder
{
    public function run()
    {
        $menus = [
            ['title' => 'Nasi Goreng Spesial', 'slug' => Str::slug('Nasi Goreng Spesial'), 'calories' => 450, 'meal_type' => 'Makan Siang', 'description' => 'Nasi goreng dengan campuran telur, ayam, dan sayuran segar, disajikan dengan acar.', 'recipe' => "1. Tumis bawang putih dan bawang merah hingga harum.\n2. Masukkan potongan ayam dan telur, aduk rata.\n3. Tambahkan nasi putih dan bumbu nasi goreng.\n4. Masak hingga bumbu meresap dan nasi goreng matang.", 'photo' => 'nasi-goreng-spesial.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Sup Ayam Kampung', 'slug' => Str::slug('Sup Ayam Kampung'), 'calories' => 320, 'meal_type' => 'Makan Malam', 'description' => 'Sup ayam kampung yang segar dengan bumbu rempah alami dan sayuran hijau.', 'recipe' => "1. Rebus ayam kampung hingga empuk.\n2. Tambahkan wortel, kentang, dan daun bawang.\n3. Beri bumbu garam, merica, dan kaldu ayam.\n4. Masak hingga sayuran matang dan kuah meresap.", 'photo' => 'sup-ayam-kampung.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Salad Sayur Segar', 'slug' => Str::slug('Salad Sayur Segar'), 'calories' => 180, 'meal_type' => 'Makan Siang', 'description' => 'Campuran selada, tomat, mentimun, dan wortel dengan dressing vinaigrette.', 'recipe' => 'Campur semua sayuran segar dan tuangkan dressing vinaigrette sebelum disajikan.', 'photo' => 'salad-sayur-segar.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Omelet Keju', 'slug' => Str::slug('Omelet Keju'), 'calories' => 250, 'meal_type' => 'Sarapan', 'description' => 'Telur dadar lembut dengan campuran keju cheddar yang meleleh.', 'recipe' => 'Kocok telur dengan keju, masak di wajan anti lengket hingga matang.', 'photo' => 'omelet-keju.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Sate Ayam Madura', 'slug' => Str::slug('Sate Ayam Madura'), 'calories' => 350, 'meal_type' => 'Makan Malam', 'description' => 'Sate ayam dengan bumbu kacang khas Madura, disajikan dengan lontong.', 'recipe' => 'Tusuk daging ayam, panggang, dan siram dengan bumbu kacang.', 'photo' => 'sate-ayam-madura.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Mie Goreng Jawa', 'slug' => Str::slug('Mie Goreng Jawa'), 'calories' => 400, 'meal_type' => 'Makan Siang', 'description' => 'Mie goreng dengan rasa manis dan gurih khas Jawa, lengkap dengan telur dan sayuran.', 'recipe' => 'Tumis bumbu, masukkan mie dan bahan pelengkap, masak hingga matang.', 'photo' => 'mie-goreng-jawa.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Pecel Sayur', 'slug' => Str::slug('Pecel Sayur'), 'calories' => 220, 'meal_type' => 'Makan Siang', 'description' => 'Sayuran rebus dengan saus kacang pedas manis yang segar.', 'recipe' => 'Rebus sayuran, siram dengan saus kacang dan taburi dengan kerupuk.', 'photo' => 'pecel-sayur.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Rendang Daging', 'slug' => Str::slug('Rendang Daging'), 'calories' => 550, 'meal_type' => 'Makan Malam', 'description' => 'Daging sapi dimasak dengan bumbu rempah khas Padang, empuk dan kaya rasa.', 'recipe' => "1. Tumis bumbu halus hingga harum.\n2. Masukkan daging dan santan.\n3. Masak dengan api kecil hingga santan menyusut dan daging empuk.", 'photo' => 'rendang-daging.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Gado-Gado', 'slug' => Str::slug('Gado-Gado'), 'calories' => 300, 'meal_type' => 'Makan Siang', 'description' => 'Campuran sayur rebus dengan saus kacang dan telur rebus.', 'recipe' => 'Susun sayur rebus, siram saus kacang, taburi bawang goreng.', 'photo' => 'gado-gado.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Ikan Bakar Jimbaran', 'slug' => Str::slug('Ikan Bakar Jimbaran'), 'calories' => 400, 'meal_type' => 'Makan Malam', 'description' => 'Ikan segar dibakar dengan bumbu Bali, disajikan dengan sambal matah.', 'recipe' => "1. Lumuri ikan dengan bumbu.\n2. Bakar hingga matang.\n3. Sajikan dengan sambal matah.", 'photo' => 'ikan-bakar-jimbaran.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Bakso Sapi', 'slug' => Str::slug('Bakso Sapi'), 'calories' => 380, 'meal_type' => 'Makan Siang', 'description' => 'Bakso sapi kenyal disajikan dengan kuah kaldu gurih, mi, dan sayur.', 'recipe' => 'Rebus bakso hingga mengapung, sajikan dengan mi dan kuah kaldu.', 'photo' => 'bakso-sapi.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Sop Buntut', 'slug' => Str::slug('Sop Buntut'), 'calories' => 480, 'meal_type' => 'Makan Malam', 'description' => 'Sup buntut sapi dengan kuah bening yang gurih dan sayuran segar.', 'recipe' => "1. Rebus buntut hingga empuk.\n2. Tambahkan bumbu dan sayur.\n3. Masak hingga sayur matang.", 'photo' => 'sop-buntut.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Tumis Kangkung', 'slug' => Str::slug('Tumis Kangkung'), 'calories' => 120, 'meal_type' => 'Makan Siang', 'description' => 'Sayur kangkung ditumis dengan bawang putih dan cabai.', 'recipe' => 'Tumis bawang dan cabai, masukkan kangkung, masak hingga layu.', 'photo' => 'tumis-kangkung.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Nasi Uduk Betawi', 'slug' => Str::slug('Nasi Uduk Betawi'), 'calories' => 500, 'meal_type' => 'Sarapan', 'description' => 'Nasi yang dimasak dengan santan dan rempah, disajikan dengan lauk pauk khas Betawi.', 'recipe' => "1. Masak nasi dengan santan dan daun pandan.\n2. Sajikan dengan ayam goreng, telur, dan sambal.", 'photo' => 'nasi-uduk-betawi.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Pisang Goreng', 'slug' => Str::slug('Pisang Goreng'), 'calories' => 220, 'meal_type' => 'Cemilan', 'description' => 'Pisang yang dibalut tepung dan digoreng hingga renyah.', 'recipe' => 'Celup pisang ke tepung, goreng hingga kuning kecoklatan.', 'photo' => 'pisang-goreng.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Es Cendol', 'slug' => Str::slug('Es Cendol'), 'calories' => 180, 'meal_type' => 'Minuman', 'description' => 'Minuman manis dari cendol, santan, dan gula merah.', 'recipe' => 'Campur cendol dengan santan dan sirup gula merah, sajikan dingin.', 'photo' => 'es-cendol.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Gudeg Jogja', 'slug' => Str::slug('Gudeg Jogja'), 'calories' => 430, 'meal_type' => 'Makan Siang', 'description' => 'Nangka muda dimasak manis dengan santan dan rempah khas Jogja.', 'recipe' => 'Masak nangka muda dengan santan dan gula merah hingga empuk dan berwarna coklat.', 'photo' => 'gudeg-jogja.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Ayam Bakar Taliwang', 'slug' => Str::slug('Ayam Bakar Taliwang'), 'calories' => 420, 'meal_type' => 'Makan Malam', 'description' => 'Ayam bakar dengan bumbu pedas khas Lombok.', 'recipe' => "1. Lumuri ayam dengan bumbu.\n2. Bakar hingga matang dan bumbu meresap.", 'photo' => 'ayam-bakar-taliwang.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Kerak Telor', 'slug' => Str::slug('Kerak Telor'), 'calories' => 300, 'meal_type' => 'Cemilan', 'description' => 'Makanan khas Betawi berupa telur bercampur ketan dengan kelapa parut.', 'recipe' => 'Campur telur dan ketan, masak di atas arang hingga kering dan kecoklatan.', 'photo' => 'kerak-telor.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Es Teler', 'slug' => Str::slug('Es Teler'), 'calories' => 210, 'meal_type' => 'Minuman', 'description' => 'Minuman segar dari campuran buah alpukat, nangka, kelapa muda, dan sirup.', 'recipe' => 'Campur buah dengan sirup dan es serut, sajikan dingin.', 'photo' => 'es-teler.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Tempe Mendoan', 'slug' => Str::slug('Tempe Mendoan'), 'calories' => 280, 'meal_type' => 'Cemilan', 'description' => 'Tempe tipis dibalut tepung dan digoreng setengah matang.', 'recipe' => 'Celup tempe ke tepung, goreng sebentar hingga setengah matang.', 'photo' => 'tempe-mendoan.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Bakmi Ayam', 'slug' => Str::slug('Bakmi Ayam'), 'calories' => 370, 'meal_type' => 'Makan Siang', 'description' => 'Mie dengan topping ayam suwir dan pangsit goreng.', 'recipe' => 'Rebus mie, tambahkan ayam suwir, kuah kaldu, dan pangsit.', 'photo' => 'bakmi-ayam.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Kue Lapis', 'slug' => Str::slug('Kue Lapis'), 'calories' => 250, 'meal_type' => 'Cemilan', 'description' => 'Kue berlapis dengan tekstur lembut dan rasa manis.', 'recipe' => 'Campur bahan, kukus lapis demi lapis hingga matang.', 'photo' => 'kue-lapis.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Es Campur', 'slug' => Str::slug('Es Campur'), 'calories' => 230, 'meal_type' => 'Minuman', 'description' => 'Minuman campuran aneka buah, agar-agar, dan sirup.', 'recipe' => 'Campur semua bahan dengan es serut dan sirup.', 'photo' => 'es-campur.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Ayam Goreng Kalasan', 'slug' => Str::slug('Ayam Goreng Kalasan'), 'calories' => 480, 'meal_type' => 'Makan Malam', 'description' => 'Ayam goreng dengan bumbu khas Kalasan yang gurih dan renyah.', 'recipe' => 'Marinasi ayam dengan bumbu, goreng hingga kuning kecoklatan.', 'photo' => 'ayam-goreng-kalasan.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Tahu Gejrot', 'slug' => Str::slug('Tahu Gejrot'), 'calories' => 190, 'meal_type' => 'Cemilan', 'description' => 'Tahu goreng dengan siraman kuah asam manis pedas khas Cirebon.', 'recipe' => 'Goreng tahu, siram dengan kuah dari bawang merah, cabai, dan gula.', 'photo' => 'tahu-gejrot.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Lontong Sayur', 'slug' => Str::slug('Lontong Sayur'), 'calories' => 420, 'meal_type' => 'Sarapan', 'description' => 'Lontong disajikan dengan sayur labu siam kuah santan dan telur rebus.', 'recipe' => 'Masak sayur labu dengan santan, sajikan dengan lontong dan telur.', 'photo' => 'lontong-sayur.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Soto Betawi', 'slug' => Str::slug('Soto Betawi'), 'calories' => 460, 'meal_type' => 'Makan Siang', 'description' => 'Sup daging sapi dengan kuah santan dan rempah khas Betawi.', 'recipe' => 'Rebus daging, tambahkan santan dan bumbu, masak hingga matang.', 'photo' => 'soto-betawi.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Rujak Buah', 'slug' => Str::slug('Rujak Buah'), 'calories' => 150, 'meal_type' => 'Cemilan', 'description' => 'Buah segar dipotong dan disajikan dengan saus pedas manis.', 'recipe' => 'Campur buah potong dengan saus kacang dan gula merah.', 'photo' => 'rujak-buah.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Nasi Padang', 'slug' => Str::slug('Nasi Padang'), 'calories' => 520, 'meal_type' => 'Makan Siang', 'description' => 'Nasi putih dengan berbagai lauk khas Padang seperti rendang dan gulai.', 'recipe' => 'Sajikan nasi dengan lauk rendang, gulai, dan sambal lado.', 'photo' => 'nasi-padang.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Pempek Palembang', 'slug' => Str::slug('Pempek Palembang'), 'calories' => 300, 'meal_type' => 'Cemilan', 'description' => 'Pempek ikan dengan kuah cuko pedas manis.', 'recipe' => 'Rebus pempek, sajikan dengan kuah cuko.', 'photo' => 'pempek-palembang.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Nasi Liwet Solo', 'slug' => Str::slug('Nasi Liwet Solo'), 'calories' => 470, 'meal_type' => 'Makan Siang', 'description' => 'Nasi gurih dengan santan dan daun salam, disajikan dengan ayam dan telur.', 'recipe' => 'Masak nasi dengan santan dan bumbu, sajikan dengan lauk pauk.', 'photo' => 'nasi-liwet-solo.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Ayam Penyet', 'slug' => Str::slug('Ayam Penyet'), 'calories' => 430, 'meal_type' => 'Makan Malam', 'description' => 'Ayam goreng yang dipenyet dengan sambal terasi pedas.', 'recipe' => 'Goreng ayam hingga matang, penyet dengan sambal terasi.', 'photo' => 'ayam-penyet.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Sop Kambing', 'slug' => Str::slug('Sop Kambing'), 'calories' => 520, 'meal_type' => 'Makan Malam', 'description' => 'Sup kambing dengan rempah dan kuah yang gurih.', 'recipe' => 'Rebus kambing dengan bumbu dan rempah hingga empuk.', 'photo' => 'sop-kambing.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Tahu Sumedang', 'slug' => Str::slug('Tahu Sumedang'), 'calories' => 210, 'meal_type' => 'Cemilan', 'description' => 'Tahu goreng khas Sumedang dengan tekstur renyah di luar dan lembut di dalam.', 'recipe' => 'Goreng tahu hingga kuning kecoklatan.', 'photo' => 'tahu-sumedang.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Nasi Kuning', 'slug' => Str::slug('Nasi Kuning'), 'calories' => 400, 'meal_type' => 'Sarapan', 'description' => 'Nasi yang dimasak dengan kunyit dan santan, biasanya disajikan dengan lauk pauk.', 'recipe' => 'Masak nasi dengan kunyit dan santan, sajikan dengan lauk.', 'photo' => 'nasi-kuning.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Lalapan', 'slug' => Str::slug('Lalapan'), 'calories' => 100, 'meal_type' => 'Makan Siang', 'description' => 'Sayur segar mentah yang biasanya disajikan bersama sambal dan lauk.', 'recipe' => 'Cuci sayur segar, sajikan bersama sambal dan lauk.', 'photo' => 'lalapan.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Gulai Ikan Patin', 'slug' => Str::slug('Gulai Ikan Patin'), 'calories' => 450, 'meal_type' => 'Makan Malam', 'description' => 'Ikan patin dimasak dengan kuah santan berempah.', 'recipe' => 'Masak ikan dengan bumbu gulai dan santan hingga matang.', 'photo' => 'gulai-ikan-patin.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Cilok Bandung', 'slug' => Str::slug('Cilok Bandung'), 'calories' => 260, 'meal_type' => 'Cemilan', 'description' => 'Bakso aci khas Bandung yang kenyal disajikan dengan saus kacang.', 'recipe' => 'Campur tepung aci dan bumbu, bentuk bulat, rebus, dan sajikan.', 'photo' => 'cilok-bandung.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Sambal Terasi', 'slug' => Str::slug('Sambal Terasi'), 'calories' => 50, 'meal_type' => 'Pelengkap', 'description' => 'Sambal pedas yang terbuat dari cabai dan terasi.', 'recipe' => 'Haluskan cabai dan terasi, tumis sebentar, sajikan.', 'photo' => 'sambal-terasi.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Tumpeng', 'slug' => Str::slug('Tumpeng'), 'calories' => 600, 'meal_type' => 'Acara', 'description' => 'Nasi kuning berbentuk kerucut disajikan dengan aneka lauk dan sayur.', 'recipe' => 'Masak nasi kuning, tata dengan lauk pauk, hias sesuai acara.', 'photo' => 'tumpeng.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Soto Ayam Lamongan', 'slug' => Str::slug('Soto Ayam Lamongan'), 'calories' => 400, 'meal_type' => 'Makan Siang', 'description' => 'Soto ayam dengan kuah bening dan koya khas Lamongan.', 'recipe' => 'Rebus ayam, buat kuah bening, tambahkan koya dan pelengkap.', 'photo' => 'soto-ayam-lamongan.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Karedok', 'slug' => Str::slug('Karedok'), 'calories' => 200, 'meal_type' => 'Cemilan', 'description' => 'Salad sayuran mentah dengan bumbu kacang.', 'recipe' => 'Campur sayur mentah, siram bumbu kacang, aduk rata.', 'photo' => 'karedok.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Ayam Betutu', 'slug' => Str::slug('Ayam Betutu'), 'calories' => 470, 'meal_type' => 'Makan Malam', 'description' => 'Ayam yang dibumbui dan dimasak dalam daun pisang khas Bali.', 'recipe' => 'Lumuri ayam dengan bumbu, bungkus dengan daun pisang, kukus dan panggang.', 'photo' => 'ayam-betutu.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Serabi Solo', 'slug' => Str::slug('Serabi Solo'), 'calories' => 220, 'meal_type' => 'Cemilan', 'description' => 'Kue tradisional berbahan tepung beras dengan kuah gula merah.', 'recipe' => 'Tuang adonan tepung, kukus, sajikan dengan kuah gula merah.', 'photo' => 'serabi-solo.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Bakwan Jagung', 'slug' => Str::slug('Bakwan Jagung'), 'calories' => 250, 'meal_type' => 'Cemilan', 'description' => 'Gorengan dari jagung manis dengan tepung dan bumbu.', 'recipe' => 'Campur jagung dengan tepung, goreng hingga kuning.', 'photo' => 'bakwan-jagung.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Nasi Campur Bali', 'slug' => Str::slug('Nasi Campur Bali'), 'calories' => 530, 'meal_type' => 'Makan Siang', 'description' => 'Nasi dengan berbagai lauk pauk khas Bali.', 'recipe' => 'Sajikan nasi dengan aneka lauk dan sambal matah.', 'photo' => 'nasi-campur-bali.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Sate Lilit', 'slug' => Str::slug('Sate Lilit'), 'calories' => 340, 'meal_type' => 'Makan Malam', 'description' => 'Sate khas Bali dari ikan cincang dibalut serai.', 'recipe' => 'Campur ikan cincang dengan bumbu, lilitkan di batang serai, bakar.', 'photo' => 'sate-lilit.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Es Kelapa Muda', 'slug' => Str::slug('Es Kelapa Muda'), 'calories' => 150, 'meal_type' => 'Minuman', 'description' => 'Air kelapa muda segar dengan daging kelapa.', 'recipe' => 'Sajikan air kelapa dengan es dan daging kelapa.', 'photo' => 'es-kelapa-muda.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Lemper Ayam', 'slug' => Str::slug('Lemper Ayam'), 'calories' => 280, 'meal_type' => 'Cemilan', 'description' => 'Lemper dari ketan isi ayam suwir berbumbu.', 'recipe' => 'Isi ketan dengan ayam suwir, bungkus daun pisang.', 'photo' => 'lemper-ayam.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Dadar Gulung', 'slug' => Str::slug('Dadar Gulung'), 'calories' => 230, 'meal_type' => 'Cemilan', 'description' => 'Kue dadar hijau isi kelapa parut manis.', 'recipe' => 'Buat dadar, isi kelapa manis, gulung dan sajikan.', 'photo' => 'dadar-gulung.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Bakso Malang', 'slug' => Str::slug('Bakso Malang'), 'calories' => 390, 'meal_type' => 'Makan Siang', 'description' => 'Bakso dengan berbagai jenis pelengkap seperti tahu dan siomay.', 'recipe' => 'Rebus bakso dan pelengkap, sajikan dengan kuah kaldu.', 'photo' => 'bakso-malang.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Es Dawet', 'slug' => Str::slug('Es Dawet'), 'calories' => 190, 'meal_type' => 'Minuman', 'description' => 'Minuman tradisional dari cendol dan santan dengan gula merah.', 'recipe' => 'Campur cendol dengan santan dan gula merah, sajikan dingin.', 'photo' => 'es-dawet.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Kue Cubit', 'slug' => Str::slug('Kue Cubit'), 'calories' => 210, 'meal_type' => 'Cemilan', 'description' => 'Kue mini manis yang populer dengan topping meses.', 'recipe' => 'Tuang adonan, beri topping, panggang sebentar.', 'photo' => 'kue-cubit.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Soto Mie Bogor', 'slug' => Str::slug('Soto Mie Bogor'), 'calories' => 410, 'meal_type' => 'Makan Siang', 'description' => 'Soto mie dengan kuah bening, bihun, dan daging sapi.', 'recipe' => 'Rebus daging dan mie, sajikan dengan kuah dan pelengkap.', 'photo' => 'soto-mie-bogor.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['title' => 'Keripik Singkong', 'slug' => Str::slug('Keripik Singkong'), 'calories' => 220, 'meal_type' => 'Cemilan', 'description' => 'Singkong tipis digoreng renyah dan gurih.', 'recipe' => 'Iris tipis singkong, goreng hingga kering.', 'photo' => 'keripik-singkong.jpg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ];

        DB::table('menus')->insert($menus);
    }
}
