<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert([
            [
                'id' => 2,
                'title' => 'Mix Salad',
                'slug' => 'mix-salad',
                'calories' => 0,
                'meal_type' => NULL,
                'description' => 'Healthy salad with a some dress',
                'photo' => 'menus/1X1idcACfjU7TOHAehOH4NjFEQJabOgBf6PIMByN.jpg',
                'created_at' => '2025-06-11 23:49:56',
                'updated_at' => '2025-06-11 23:49:56',
            ],
            [
                'id' => 3,
                'title' => 'Nasi Goreng Spesial',
                'slug' => 'nasi-goreng-spesial',
                'calories' => 332,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Nasi Goreng Spesial yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 4,
                'title' => 'Sate Ayam (10 tusuk)',
                'slug' => 'sate-ayam-10-tusuk',
                'calories' => 350,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Sate Ayam (10 tusuk) yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 5,
                'title' => 'Rendang Daging Sapi',
                'slug' => 'rendang-daging-sapi',
                'calories' => 468,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Rendang Daging Sapi yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 6,
                'title' => 'Gado-gado',
                'slug' => 'gado-gado',
                'calories' => 295,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Gado-gado yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 7,
                'title' => 'Soto Ayam',
                'slug' => 'soto-ayam',
                'calories' => 136,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Soto Ayam yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 8,
                'title' => 'Bubur Ayam',
                'slug' => 'bubur-ayam',
                'calories' => 372,
                'meal_type' => 'breakfast',
                'description' => 'Sajian lezat Bubur Ayam yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 9,
                'title' => 'Ayam Goreng',
                'slug' => 'ayam-goreng',
                'calories' => 260,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Ayam Goreng yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 10,
                'title' => 'Ikan Bakar',
                'slug' => 'ikan-bakar',
                'calories' => 139,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Ikan Bakar yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 11,
                'title' => 'Mie Ayam Bakso',
                'slug' => 'mie-ayam-bakso',
                'calories' => 400,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Mie Ayam Bakso yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 12,
                'title' => 'Capcay Goreng',
                'slug' => 'capcay-goreng',
                'calories' => 115,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Capcay Goreng yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 13,
                'title' => 'Lontong Sayur',
                'slug' => 'lontong-sayur',
                'calories' => 357,
                'meal_type' => 'breakfast',
                'description' => 'Sajian lezat Lontong Sayur yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 14,
                'title' => 'Gulai Kambing',
                'slug' => 'gulai-kambing',
                'calories' => 151,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Gulai Kambing yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 15,
                'title' => 'Ketoprak',
                'slug' => 'ketoprak',
                'calories' => 470,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Ketoprak yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 16,
                'title' => 'Nasi Uduk',
                'slug' => 'nasi-uduk',
                'calories' => 260,
                'meal_type' => 'breakfast',
                'description' => 'Sajian lezat Nasi Uduk yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 17,
                'title' => 'Sayur Asem',
                'slug' => 'sayur-asem',
                'calories' => 80,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Sayur Asem yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 18,
                'title' => 'Pepes Ikan Mas',
                'slug' => 'pepes-ikan-mas',
                'calories' => 143,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Pepes Ikan Mas yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 19,
                'title' => 'Tahu Goreng',
                'slug' => 'tahu-goreng',
                'calories' => 111,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Tahu Goreng yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 20,
                'title' => 'Tempe Bacem',
                'slug' => 'tempe-bacem',
                'calories' => 157,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Tempe Bacem yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 21,
                'title' => 'Perkedel Kentang',
                'slug' => 'perkedel-kentang',
                'calories' => 69,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Perkedel Kentang yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 22,
                'title' => 'Opor Ayam',
                'slug' => 'opor-ayam',
                'calories' => 290,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Opor Ayam yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 23,
                'title' => 'Rawon',
                'slug' => 'rawon',
                'calories' => 280,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Rawon yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 24,
                'title' => 'Sop Buntut',
                'slug' => 'sop-buntut',
                'calories' => 250,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Sop Buntut yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 25,
                'title' => 'Martabak Telur',
                'slug' => 'martabak-telur',
                'calories' => 268,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Martabak Telur yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 26,
                'title' => 'Pempek Kapal Selam',
                'slug' => 'pempek-kapal-selam',
                'calories' => 384,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Pempek Kapal Selam yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 27,
                'title' => 'Bakwan Sayur',
                'slug' => 'bakwan-sayur',
                'calories' => 137,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Bakwan Sayur yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 28,
                'title' => 'Siomay Ikan',
                'slug' => 'siomay-ikan',
                'calories' => 362,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Siomay Ikan yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 29,
                'title' => 'Cah Kangkung',
                'slug' => 'cah-kangkung',
                'calories' => 89,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Cah Kangkung yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 30,
                'title' => 'Nasi Kuning',
                'slug' => 'nasi-kuning',
                'calories' => 260,
                'meal_type' => 'breakfast',
                'description' => 'Sajian lezat Nasi Kuning yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 31,
                'title' => 'Sambal Goreng Kentang',
                'slug' => 'sambal-goreng-kentang',
                'calories' => 119,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Sambal Goreng Kentang yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 32,
                'title' => 'Sayur Lodeh',
                'slug' => 'sayur-lodeh',
                'calories' => 123,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Sayur Lodeh yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 33,
                'title' => 'Telur Balado',
                'slug' => 'telur-balado',
                'calories' => 150,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Telur Balado yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 34,
                'title' => 'Ayam Bakar',
                'slug' => 'ayam-bakar',
                'calories' => 164,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Ayam Bakar yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 35,
                'title' => 'Urap Sayuran',
                'slug' => 'urap-sayuran',
                'calories' => 96,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Urap Sayuran yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 36,
                'title' => 'Tongseng Kambing',
                'slug' => 'tongseng-kambing',
                'calories' => 332,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Tongseng Kambing yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 37,
                'title' => 'Gudeg',
                'slug' => 'gudeg',
                'calories' => 160,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Gudeg yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 38,
                'title' => 'Ikan Tongkol Balado',
                'slug' => 'ikan-tongkol-balado',
                'calories' => 200,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Ikan Tongkol Balado yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 39,
                'title' => 'Semur Daging',
                'slug' => 'semur-daging',
                'calories' => 250,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Semur Daging yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 40,
                'title' => 'Kerupuk Udang',
                'slug' => 'kerupuk-udang',
                'calories' => 44,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Kerupuk Udang yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 41,
                'title' => 'Sate Padang',
                'slug' => 'sate-padang',
                'calories' => 465,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Sate Padang yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 42,
                'title' => 'Empal Gentong',
                'slug' => 'empal-gentong',
                'calories' => 290,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Empal Gentong yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 43,
                'title' => 'Asinan Sayur',
                'slug' => 'asinan-sayur',
                'calories' => 130,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Asinan Sayur yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 44,
                'title' => 'Pecel Lele',
                'slug' => 'pecel-lele',
                'calories' => 290,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Pecel Lele yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 45,
                'title' => 'Krengsengan Daging',
                'slug' => 'krengsengan-daging',
                'calories' => 300,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Krengsengan Daging yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 46,
                'title' => 'Sop Konro',
                'slug' => 'sop-konro',
                'calories' => 400,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Sop Konro yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 47,
                'title' => 'Laksa Bogor',
                'slug' => 'laksa-bogor',
                'calories' => 350,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Laksa Bogor yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 48,
                'title' => 'Nasi Liwet',
                'slug' => 'nasi-liwet',
                'calories' => 300,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Nasi Liwet yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 49,
                'title' => 'Coto Makassar',
                'slug' => 'coto-makassar',
                'calories' => 400,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Coto Makassar yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 50,
                'title' => 'Sate Maranggi',
                'slug' => 'sate-maranggi',
                'calories' => 380,
                'meal_type' => 'dinner',
                'description' => 'Sajian lezat Sate Maranggi yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 51,
                'title' => 'Ketupat Sayur',
                'slug' => 'ketupat-sayur',
                'calories' => 357,
                'meal_type' => 'breakfast',
                'description' => 'Sajian lezat Ketupat Sayur yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
            [
                'id' => 52,
                'title' => 'Ikan Asin Gabus',
                'slug' => 'ikan-asin-gabus',
                'calories' => 200,
                'meal_type' => 'lunch',
                'description' => 'Sajian lezat Ikan Asin Gabus yang penuh gizi.',
                'photo' => NULL,
                'created_at' => '2025-06-13 05:12:08',
                'updated_at' => '2025-06-13 05:12:08',
            ],
        ]);
        DB::statement('ALTER TABLE menus AUTO_INCREMENT = 53;');
    }
}